### ISSUE TITLE
Error importing library

### ISSUE THREAD

**Issue by aazuspan** [davidtheobald8/landscapen#2]
Hi there! This looks like a really promising library, but I haven't been able to access it. 

Running `var lse = require('users/DavidTheobald8/modules:lse')` throws `Cannot find required repo: users/DavidTheobald8/modules:lse`. 

I think the issue is that your GEE repository was either deleted or is not set to public. If you still want to share it, you can go to the repo settings in the code editor and check "Anyone can read".  

Also, just a quick heads up, the link to your website in the readme is broken. 

Thanks!

EDIT: My old explanation of what was causing the issue was wrong, so I updated it.

**Comment by mkwrigh1** [comment]
> 
> 
> Hi there! This looks like a really promising library, but I haven't been able to access it.
> 
> Running `var lse = require('users/DavidTheobald8/modules:lse')` throws `Cannot find required repo: users/DavidTheobald8/modules:lse`.
> 
> I think the issue is that your GEE repository was either deleted or is not set to public. If you still want to share it, you can go to the repo settings in the code editor and check "Anyone can read".
> 
> Also, just a quick heads up, the link to your website in the readme is broken.
> 
> Thanks!
> 
> EDIT: My old explanation of what was causing the issue was wrong, so I updated it.

I am also encountering the same error, but I would love to use this library!

**Comment by trejopedro21** [comment]
Hello. Still not available.  I think is the only library that provides landscape metrics in GEE. Waiting for any information.
Regards!

**Comment by davidtheobald8** [comment]
Apologies. I haven't had the resources to keep this up to date.
